environment:
   QTDIR: C:\Qt\5.6\mingw53_32

install:
  - set QTDIR=C:\Qt\5.6\mingw53_32
  - set PATH=%PATH%;C:\Qt\5.6\mingw53_32\bin;C:\Qt\5.6\mingw53_32;C:\Qt\5.6;%MINGW%\bin
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake mupen64plus-gui.pro
    
build_script:
  - make -j`nproc`
