environment:
    matrix:
    - QTDIR: C:\Qt\5.6\mingw53_32
      cname: mingw
    - QTDIR: C:\Qt\5.11\mingw53_32
      cname: mingw

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake mupen64plus-gui.pro
    
build_script:
  - make -j`nproc`
