image: Visual Studio 2015

install:
 - set QTVER=5.12.1
 - set SDL2_VERSION=2.0.6
 - set MINGW_PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
 - set PATH=%PATH%;C:\Qt\%QTVER%\mingw73_64;C:\Qt\%QTVER%\mingw73_64\bin;C:\Qt\Tools\QtCreator\bin;%MINGW_PATH%\bin
 - IF NOT EXIST SDL2-devel-%SDL2_VERSION%-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
 - 7z x SDL2-devel-%SDL2_VERSION%-mingw.tar.gz -so | 7z x -si -ttar
  
 - qmake mupen64plus-gui-av.pro
    
build_script:
  - mingw32-make 

after_build:
  - md m64fl
  - copy release\*.exe m64fl
  - copy C:\projects\mupen64plus-gui\SDL2-2.0.6\x86_64-w64-mingw32\bin\sdl2.dll m64fl
  - windeployqt m64fl
  - 7z a m64fl.zip m64fl
    
cache:
  - SDL2-devel-2.0.6-mingw.tar.gz
 
artifacts:
  - path: release\mupen64plus-gui.exe
    name: m64fl-build
  - path: .\m64fl.zip
    name: m64fl-windeploy
