image: Visual Studio 2015

install:
 - set QTDIR=C:\Qt\latest\mingw53_32
 - set PATH=%PATH%;C:\Qt\5.11\mingw53_32;C:\Qt\5.11\mingw53_32\bin;C:\Qt\Tools\QtCreator\bin;C:\MinGW\bin
 - ps: Start-FileDownload https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip -FileName sdl2.zip
 - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
 - set LIB=%LIB%;C:\projects\mupen64plus-gui\sdl2\SDL2-2.0.5\lib\x86
 - ps: Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip -FileName sdl2_mixer.zip
 - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
 - set LIB=%LIB%;C:\projects\mupen64plus-gui\sdl2_mixer\SDL2_mixer-2.0.1\lib\x86;C:\projects\mupen64plus-gui\sdl2\SDL2-2.0.5\include
 - ps: Get-ChildItem -Recurse -Depth 4
 - gcc -v
 - qmake mupen64plus-gui.pro
    
build_script:
  - mingw32-make 
