environment:
  matrix:
    - QTDIR: C:\Qt\5.6.3\mingw49_32
    - QTDIR: C:\Qt\5.6.3\msvc2013
    - QTDIR: C:\Qt\5.6.3\msvc2013_64
    - QTDIR: C:\Qt\5.6.3\msvc2015
    - QTDIR: C:\Qt\5.6.3\msvc2015_64
    - QTDIR: C:\Qt\5.7\mingw53_32
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.9.5\mingw53_32
    - QTDIR: C:\Qt\5.9.5\msvc2013_64
    - QTDIR: C:\Qt\5.9.5\msvc2015
    - QTDIR: C:\Qt\5.9.5\msvc2015_64
    - QTDIR: C:\Qt\5.10.1\mingw53_32
    - QTDIR: C:\Qt\5.10.1\msvc2013_64
    - QTDIR: C:\Qt\5.10.1\msvc2015
    - QTDIR: C:\Qt\5.10.1\msvc2015_64
    - QTDIR: C:\Qt\5.11.1\mingw53_32
    - QTDIR: C:\Qt\5.11.1\msvc2015
    - QTDIR: C:\Qt\5.11.1\msvc2015_64

install:
  - qmake mupen64plus-gui.pro
    
build_script:
  - make -j`nproc`
