language: c

compiler:
  - gcc
  - clang

install: true

addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
